### ISSUE TITLE
Missing Brackets while Squaring Expressions

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#284] opened 2017-06-20 13:44 UTC
Related to #273 but keeping it separate for organization. The following is what I would like printed.
![2017-06-20 1](https://user-images.githubusercontent.com/26230851/27336169-bb922868-559c-11e7-8f95-82a89827d123.png)

This is what I typed for the first expression in the equation.
```
((C slopeHght)-(C slipHght )):^(Int 2):/(Int 2) :* (C satWeight) +
((C waterHght)-(C slopeHght)):^(Int 2) :* (C satWeight)
```

And this is what was generated.
![2017-06-20](https://user-images.githubusercontent.com/26230851/27336210-d9dd2ef8-559c-11e7-97fe-331cf31c8abe.png)

To point out the issue, brackets are missing around the (y_u,i - y_slip,i)^2 part.

**Comment by njericha** [comment] 2017-06-20 14:56
![2017-06-20 2](https://user-images.githubusercontent.com/26230851/27339790-be56a7b8-55a6-11e7-99df-1e1065b76882.png)

```
(C intNormForce)*((Int 1)-(C SM.poissnsR)) /
(((Int 1)+(C SM.poissnsR)) :* ((Int 1) :- (Int 2):*(C SM.poissnsR) :+ (C baseWthX)))
```

Another case of missing brackets, this time with `:*`

**Comment by szymczdm** [comment] 2017-06-21 20:08
I've updated this as of 45dc8f132871d51dcc2e998bac423748bfc6de00 can you please check if everything has been updated correctly (and double check that no new bugs have arisen)?

If it all looks good, we can close this issue.

**Comment by njericha** [comment] 2017-06-22 13:24
All the brackets look good. Not sure if this is new or not but this came up. The original document has "0.01*fraction" but the way this is laid out looks like its is "1.0*e minus 2*fraction"

![2017-06-22](https://user-images.githubusercontent.com/26230851/27436126-41bdecfc-572c-11e7-9492-c48cff478807.png)
@szymczdm

**Comment by JacquesCarette** [comment] 2017-06-22 14:58
Are they mathematically equivalent?

**Comment by njericha** [comment] 2017-06-22 15:01
`0.01*fraction` is equal to `1.0e-2 * fraction`. The problem is that is looks like `(1.0*e) - (2*fraction)`

**Comment by JacquesCarette** [comment] 2017-06-22 17:11
I could not parse that correctly, which is why I was confused.  Now that I parse it as intended, it is indeed obvious that they are mathematically equivalent, but it looks all wrong!  Please file a separate issue for this.  I think the issue which started this is fixed.

**Closed** 2017-06-22 17:14 UTC
Labels: bug, Expressions
