### ISSUE TITLE
Revise and Update Section 5.2 for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#257] opened 2017-06-06 16:53 UTC
Created this issue in order to close issue #252.
As stated by Dr. Smith, the following needs to be updated/improved:

- the response type is listed as an input, but in A7 the response type is included as an assumption
- documentation of use cases doesn't really fit, since the program only has one use case, not two (input and output are not separate use cases)

**Comment by smiths** [comment] 2017-06-06 17:39
Thank you for creating this issue @niazim3.  Now we can be sure to not forget to address these concerns.

**Comment by niazim3** [comment] 2017-06-26 16:00
Update: commit 11bf0be caused section 5.2 to be defined as `s5_2_bullets` being passed into the function `scopeOfTehPrjF` defined in the file Example/Drasil/Sections/ScopeOfTheProject.hs.

**Comment by niazim3** [comment] 2017-07-31 14:06
![image](https://user-images.githubusercontent.com/28247301/28780699-b88db642-75d5-11e7-8e5b-d2cf99577754.png)

The current output is displayed in the left side of the above screenshot, and the right side displays the current desired output in the CaseStudies version of GlassBR. With the exception of the highlighted output, the two documents are essentially the same.

- Currently, to create the section, simply the definition of `glassGeo` is being output; I'm a bit hesitant to remove **response type** from the definition of glass geometry, since it is obviously important information, but just happens to be used in the wrong context... should an alterred definition be input verbatim for now? @smiths 
- Also, is the end goal of this issue to merge the two use cases into one use case?

**Comment by smiths** [comment] 2017-07-31 14:27
I am fine with the generated text.  There is no need for capacity > demand in equation form.  Saying it in words is fine.  

I agree that response type is not part of the glass geometry.  Isn't response type its own chunk?  I haven't looked at the Drasil code, but Use Case 1 (the inputs) looks like the definitions of the input variables.  I would think that response type is a separate input variable.

Yes, we should only have one use case.  What is currently Use Case 1 is the inputs and what is Use Case 2 is the outputs.  The single use case should be something like: "read in the inputs and output the results."  @niazim3, can you create an issue for this and then assign it to yourself?

**Comment by niazim3** [comment] 2017-07-31 15:06
Response type is not currently it's own chunk, as the only place it is defined is in the definition of the `glassGeo` `ConceptChunk` as follows:
``` Haskell 
glassGeo      = dcc "glassGeo"    (nounPhraseSP "glass geometry")```
  ("The glass geometry based inputs include the dimensions of the glass " ++
    "plane, glass type and response type.")

**Comment by niazim3** [comment] 2017-07-31 15:06
I suppose what can be done is:

- create a chunk for glass plane
- create a chunk for response type
- (chunk for glass type already exists)
- leave the definition of `glassGeo` as it is
- call a list of chunks in the Use Cases section instead of using the definition for `glassGeo`

**Comment by smiths** [comment] 2017-07-31 15:16
Is response type even an input?  I didn't realize that the only place it appears in the document is in this Use Case.  I just looked at the inputs for GlassBR and I do not see a response type as an input.  I wonder if response type was intended to be a shorthand for the other inputs (weight of charge, tnt equivalent factor etc.)

**Comment by niazim3** [comment] 2017-07-31 15:26
I don't believe response type is an input. The only inputs that GlassBR takes are Pbtol, length of glass, width of glass, nominal thickness, glass type, weight charge, tnt equivalent factor, and stand off distance.
As you stated in issue #252, response type is mentioned in assumptions (A7: The response type considered in GlassBR is flexural.) After searching up what "flexural" means, I don't think response type was intended to be shorthand for other inputs, but I may be incorrect...

**Comment by smiths** [comment] 2017-07-31 15:52
Response type in the use case is a mistake.  We can either replace it with the description of all the inputs, or a generic phrase that means, "and other inputs."  Can you correct the input use case to list all of the inputs (not just the geometry)?  We can then have a look at how that appears.  If it is too verbose, we can think about a way to shorten it.

**Comment by niazim3** [comment] 2017-07-31 16:11
Replacing the sentence with all the inputs produces the following:

![image](https://user-images.githubusercontent.com/28247301/28787114-4c0781e2-75e9-11e7-8f44-b0a6308cc77b.png)

Personally, I liked how the inputs were sort of grouped together. What if we were to tweak the original to output something similar to the following?
"The user provides the inputs to GlassBR for use within the analysis. There are two **main** classes of inputs: glass geometry and blast type. The glass geometry based inputs include the dimensions of the glass plane and glass type. The blast type input includes parameters like weight of charge, TNT equivalent factor and stand off distance from the point of explosion. These parameters describe charge weight and stand off blast. Another input the user gives is the tolerable value of probability of breakage."

**Comment by smiths** [comment] 2017-08-01 15:45
@niazim3 , I agree that your second option (the one in quotes) is much better than the one where each input is defined in turn.  In fact, I was going to make the same suggestion after reading the generated version.  The purpose of the use case description is to give the reader a feel for the inputs of the software, but it can be more abstract than simply a list of inputs with their descriptions.  If we just want a list of inputs and their descriptions, we would be better of producing a table of inputs, like in the requirements. Doing the same thing under the use case heading would be redundant.

Please proceed with using your proposed (tweaked) text.

**Comment by niazim3** [comment] 2017-08-01 16:22
Thank you for the feedback @smiths. The changes have been made in commit 5e3bdd5. 
Should section 5.1 also be altered?
The current output is:
![image](https://user-images.githubusercontent.com/28247301/28835574-cce73576-76b3-11e7-817b-f36d967c85e2.png)
Would removing the first 2 columns from the above table make sense?

**Comment by smiths** [comment] 2017-08-01 18:46
Thank you @niazim3.  Looks good.  Yes, please remove the first two columns from the Use Case Table.  There is only one use case.  It is okay to say that this use case has two actors.

**Closed** 2017-08-01 19:38 UTC
Labels: Low Priority
