### ISSUE TITLE
Allow Indexing for Exprs

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#352] opened 2017-07-18 15:33 UTC
As mentioned in the comments of commit 080e4d7 (related to #328), we run into errors when attempting to index a list (since **[]** expects an `Int` but the variables that need to be passed in are `Expr`s).

**Comment by njericha** [comment] 2017-07-18 15:49
duplicate of #265 ?

**Comment by palmerst** [comment] 2017-07-20 14:06
Indexing added to Expr in  f682d82

**Closed** 2017-07-20 14:06 UTC
Labels: Expressions
