### ISSUE TITLE
Automating the generation of Descriptions for DataDefns, InModels, and ThModels

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#220] opened 2017-05-26 14:19 UTC
The following is a categorization of the implementation of the "is the" pattern found within GlassBR, specifically from the _Theoretical Models_ and _Instance Models_.
![image](https://cloud.githubusercontent.com/assets/28247301/26497874/0a55016a-41fb-11e7-8eb5-e7f60bf6c3b1.png)
However, it seems that _DataDefns_ already has this pattern automatically generated?
`s6_2_4_DDefns ::[Contents] 
s6_2_4_DDefns = map Definition (map Data dataDefns)`
where 
`dataDefns :: [QDefinition]
dataDefns = [risk,hFromt,loadDF,strDisFac,nonFL,glaTyFac,dL,tolPre,tolStrDisFac]`.
How are the "is the"s automatically generated? @szymczdm 
That is, how does calling the following example
`risk :: QDefinition
risk = fromEqn' (risk_fun ^. id) (nounPhraseSP "risk of failure") (risk_fun ^. symbol) risk_eq`
result in:
![image](https://cloud.githubusercontent.com/assets/28247301/26498323/abac27e0-41fc-11e7-96a3-154c611611b7.png)

**Comment by JacquesCarette** [comment] 2017-05-26 20:31
Very well spotted.  Have you made some headway on this, or do you require some help?

**Comment by niazim3** [comment] 2017-05-26 20:55
Unfortunately, I haven't progressed much on this particular issue today, so help would be greatly appreciated. :)

**Comment by niazim3** [comment] 2017-05-30 13:59
It seems that the `getDefName` and `repUnd` functions (from **Document.hs** and **RefHelpers.hs** respectively) are responsible for the automatic labelling for the definition within Drasil.
I also found a `descLines` within **HTML.Import.hs** and **TeX.Import.hs**,  which "builds each line of the description of a data def".

**Comment by JacquesCarette** [comment] 2017-05-30 14:19
We need to change the API of each of these functions to that it gets passed the right kind of `Chunk` which has an abbreviation in it that can be used for a label.  `descLines` should probably take an extra parameter as input (no a `Chunk`, since those are gone by the time that part of the back-end is reached).

**Comment by niazim3** [comment] 2017-06-01 19:44
Update: Commit 45064d2 --> created `isThe` and `isThe'` combinators to reduce some of the uses of the Sentence type.

**Comment by njericha** [comment] 2017-06-14 17:21
Also related to #29

**Comment by njericha** [comment] 2017-07-26 17:36
Duplicate of #29

**Closed by njericha** 2017-07-26 17:36 UTC
Labels: duplicate, question
