### ISSUE TITLE
Person information should not be duplicated in citations

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#378] opened 2017-08-11 02:40 UTC
Whenever a `Person` exists in our database, and that person is an author of a paper, that person's information should be pulled from the database, not duplicated.

- [x] GlassBR
- [x] SSP
- [x] NoPCM
- [x] GamePhysics
- [x] SWHS

**Comment by hmadej** [comment] 2017-08-11 13:27
Should these people be put with Authors, or a separate "Person" file.

**Comment by JacquesCarette** [comment] 2017-08-11 13:38
Good question!  Do we just have authors right now?  My instincts is to define persons as the larger set, and then to add information to those persons who are authors in an authors file.

**Comment by njericha** [comment] 2017-08-11 13:44
0fb168baaad10439fabeb282aef7e9af7cc20c9d Will help with avoiding duplication.

**Comment by hmadej** [comment] 2017-08-11 13:50
added People file, right now duplicate of authors but people who are not authors can also be added. d871a21

**Comment by danscime** [comment] 2017-08-11 16:12
What would the difference be between a person and an other? Would it be better to just have a database of growing information on people so that they can be used as authors or editors or anything? Like only have people in one file?

**Comment by JacquesCarette** [comment] 2017-08-11 16:57
An author is a special kind of person.  A set of growing databases of people (not just one, as it will eventually grow too large).  So yes, my point was to have a database of people who can be used in all sorts of roles.

**Comment by danscime** [comment] 2017-08-14 13:23
For now, I'll put everyone into the "People" file and remove the author file

**Comment by hmadej** [comment] 2017-08-14 13:39
don't remove the author's file it is used throughout the everyones examples.

**Comment by danscime** [comment] 2017-08-14 13:45
I'm going through and fixing imports for every example so that people are pulled from people

**Comment by danscime** [comment] 2017-08-14 14:13
Removed Authors and alphabetized people by last name, updated everyone's imports to take people
2f7ba53cfbd2d40082bf227c669e5f7af9cddeac

**Closed** 2017-08-17 13:46 UTC
