### ISSUE TITLE
Repeated description

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#41] opened 2016-06-23 19:54 UTC
I changed from using RelationChunk to EqChunk for the Data Definition Section since I thought I should use the information capture function that Drasil provides. But there'll be a problem if the "Equation" is actually a function. For example, as the screenshot below shows, the description for q̂tol repeats since it appears twice in this Expr.

![screen shot 2016-06-24 at 3 20 06 am](https://cloud.githubusercontent.com/assets/19175468/16316819/b9284eee-39ba-11e6-943d-0161d7e0080c.png)

For this case, should I change it back to RelationChunk since it's more like a relation instead of an equation? Or do we also need to consider about functions in EqChunk and avoid repeating? (We might need to avoid this problem since we want automation for Theoretical Model and Instance Model as well in the end.)

**Comment by JacquesCarette** [comment] 2016-06-24 01:42
Spencer should definitely say something about this one -- the issue is not so much between the various chunks as one of a bad convention (in the original SRS, not you).  What the above says is that q_{tol} is really a function, but that in writing, we'll elide the parameters.  I think.  Clearly the RHS above is not a proper definition, as it is circular!

**Comment by smiths** [comment] 2016-07-15 21:03
Yes, the original SRS uses a "bad" convention, but for this case it is not entirely clear to write it.  The notation that f = f(x, y, z) is very common in physics, but that isn't a good excuse.  :-)

To further explain the situation, we should look at the actual data definition for q hat.  The data definition given above is not actually complete.  q hat is not easily defined in an equation, especially not an explicit equation.  In the original SRS, q hat is defined in words.  The following shows the definition:

![dd8](https://cloud.githubusercontent.com/assets/1422000/16888297/2790106c-4aad-11e6-9cb7-8b76035f8cba.png)

q hat is found by interpolation using the aspect ratio and J from the following Figure:

![fig3](https://cloud.githubusercontent.com/assets/1422000/16888332/5a3b157a-4aad-11e6-8e3e-b448c98a23a4.png)

How to represent this in an equation is unclear to me.  I suppose we could introduce an "interpolate" function that is never explicitly defined.  We could also go further and explain the algorithm for interpolation, but this is bringing details into the SRS that potentially make it less abstract.

I'm afraid that I do not have a resolution, only a recommendation that we discuss this further.  :-)

**Comment by JacquesCarette** [comment] 2016-07-15 22:09
I think there are two completely different issues here:

1. using f as an abbreviation for f(a,b,z)
2. defining a particular quantity (like q hat) via interpolation in a graph/Figure.

I think the first is easy to handle: even though an equation is written down, it is actually the definition of an abbreviation.  That is a separate concept that we need to introduce.

The second is indeed trickier to deal with.  Especially as it is interpolation from a Figure, rather than from an equation.  As far as I can tell, (q hat) is not computable by a program, it must somehow always be given numerically, as I don't know how to instruct a computer how to "interpolate from a Figure"!!!  That part then too needs more thinking.

**Comment by smiths** [comment] 2016-07-16 12:42
Thank you for your feedback Jacques.  I like your idea of an abbreviation.  That seems like a good concept to introduce to Drasil.  With respect to q hat, I could come up with a way to write it down as an algorithm, by viewing the information in the Figure in tabular form.  That is how it is calculated by the program.  I think the question for us to discuss is how much design should happen in the requirements specification.  The original plan was to keep the specification abstract, but maybe it is too abstract for Drasil to do anything meaningful with it?

**Comment by JacquesCarette** [comment] 2016-07-18 18:18
I really don't know what the best way to handle the "defining q hat" question in the requirements is.  Maybe this is a Drasil design question best handled by @smiths ?

**Comment by smiths** [comment] 2016-07-18 18:27
I think the best way to decide how to proceed is to write the more specific requirements for q hat and then judge whether we like them or not.  I'll give this a try, so I'll create an issue and assign it to myself.

**Comment by szymczdm** [comment] 2017-01-16 15:52
Since this issue has been broken down a bit, it looks like we'll be waiting on #55 / #106 and #16

**Comment by smiths** [comment] 2017-05-30 14:27
A mathematical model of how to calculate q is now available at:
CaseStudies/glass/Documentation/MIS/MathModelForCalc_q.pdf

**Closed** 2017-07-26 18:56 UTC
