### ISSUE TITLE
Should we allow multiple different unit names for the same units?

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#90] opened 2016-11-08 18:37 UTC
Some units are equivalent, but (sometimes) go by different names. For example: torqueU / momentOfForceU and springConstU / stiffnessU from SI_Units.

Should we have multiple copies with different names, or collapse them into one "chosen" name (possibly something more general)?

**Comment by smiths** [comment] 2016-11-08 18:56
The following wikipedia page does a good job of explaining the terminology of torque, moment of force and moment.  Engineers in the UK and the US use the terms slightly differently.  In some cases torque is reserved for dynamics problem (change in angular momentum) and in other cases torque is used for both dynamic and static problems.

What about introducing the idea of a synonym?  We can define the concept using our version of the terminology, but allow for synonyms that can give the same concept a different name?

With respect to stiffness versus spring constants, stiffness is a more general concept.  A spring has stiffness, but so does a metal bar, or a structure.  I guess we could think of spring stiffness as a special case of stiffness in general?

**Comment by JacquesCarette** [comment] 2016-11-08 19:25
Looks like you forgot to past in the link?

Yes, synonyms will definitely be needed!  And 'specialization' is a special kind of synonym.

**Comment by smiths** [comment] 2016-11-08 20:10
Oops.  Here is the link I was referring to:

https://en.wikipedia.org/wiki/Torque

Here is another one that discusses stiffness:

https://en.wikipedia.org/wiki/Stiffness

**Comment by njericha** [comment] 2017-06-16 18:35
This is now a duplicate of #166

**Closed by njericha** 2017-06-16 18:35 UTC
Labels: Design
