### ISSUE TITLE
Proper way to Parametrize conVar

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#124] opened 2017-05-04 16:56 UTC
Right now I am using a hack to parametrize unit vector for unitals in gamephys example:

Unit vector is the "basic concept" and the example has a "horizontal" unit vector and "vertical" unit vector.

iVect       = ucFromVC ivec metre
            where ivec = cvR (dcc "unit_vect" (compoundPhrase' (cn "horizontal") (QM.unit_vect ^. term)) "unit vector" ) (QM.unit_vect ^. symbol)

is there a better way of doing this?

**Comment by JacquesCarette** [comment] 2017-05-04 17:43
I don't think there is a better way to do this yet; we need to invent one, and then implement it.

This is not so straightforward.  We could 'do better' for 2D, but then that won't scale.  Plus it is hard to see 'unit_vector' as fundamental, as opposed to seeing it being made up of vector coupled with length=1.  Having said that, I have encountered situations where a simple change of perspective (i.e. such as making unit_vector fundamental) simplifies things a lot.  Long-winded comment to say 'needs design'.

**Comment by njericha** [comment] 2017-07-17 18:01
duplicate of #91

**Closed by njericha** 2017-07-17 18:01 UTC
Labels: Design
